### ISSUE TITLE
Raw data doesnt Match at all to the Target

### ISSUE THREAD

**Issue by angelooo18** [jaakkopasanen/AutoEq#371] opened 2021-11-26 19:59 UTC
Trying to convert raw data of KZ ZSN Pro X to Sony IER-Z1R both measured with IEC60318-4, using this line code:
`autoeq.py --input_dir="my_data/KZ ZSN Pro X IEC6/" --compensation="Targets/Sony IER-Z1R IEC6.csv" --treble_f_lower=22000 --treble_f_upper=22050 --max_gain=1.7976931348623157e+308 --equalize --parametric_eq --max_filters=10+10+10+10+10+10 --output_dir="my_results/Sony IER-Z1R IEC6"
`
The plot show this result:
![KZ ZSN Pro X](https://user-images.githubusercontent.com/51036845/143625353-c0eece4a-e1f4-4a91-ad9d-6fe712001606.png)
with these PEQ:
`Preamp: -3.0 dB
Filter 1: ON PK Fc 52 Hz Gain 0.5 dB Q 0.55
Filter 2: ON PK Fc 287 Hz Gain -1.2 dB Q 0.69
Filter 3: ON PK Fc 1068 Hz Gain 3.6 dB Q 0.61
Filter 4: ON PK Fc 2590 Hz Gain -8.3 dB Q 1.73
Filter 5: ON PK Fc 3791 Hz Gain 4.7 dB Q 3.51
Filter 6: ON PK Fc 5037 Hz Gain -5.0 dB Q 3.12
Filter 7: ON PK Fc 6464 Hz Gain 2.9 dB Q 5.85
Filter 8: ON PK Fc 12401 Hz Gain 7.2 dB Q 1.17
Filter 9: ON PK Fc 16655 Hz Gain -11.9 dB Q 0.52
Filter 10: ON PK Fc 19929 Hz Gain -6.6 dB Q 1.99
Filter 11: ON PK Fc 7169 Hz Gain 1.4 dB Q 4.40
Filter 12: ON PK Fc 8058 Hz Gain -3.3 dB Q 3.76
Filter 13: ON PK Fc 10596 Hz Gain 2.5 dB Q 2.33
Filter 14: ON PK Fc 12518 Hz Gain -3.2 dB Q 3.17
Filter 15: ON PK Fc 14788 Hz Gain 2.7 dB Q 2.15
Filter 16: ON PK Fc 16143 Hz Gain -3.2 dB Q 4.26
Filter 17: ON PK Fc 22047 Hz Gain 0.1 dB Q 1.85
Filter 18: ON PK Fc 7175 Hz Gain 0.2 dB Q 2.54
Filter 19: ON PK Fc 9409 Hz Gain -0.6 dB Q 2.06
Filter 20: ON PK Fc 9800 Hz Gain 0.2 dB Q 2.31
Filter 21: ON PK Fc 12748 Hz Gain 0.4 dB Q 1.36
Filter 22: ON PK Fc 14627 Hz Gain -0.8 dB Q 4.27
Filter 23: ON PK Fc 19420 Hz Gain -0.3 dB Q 2.85
Filter 24: ON PK Fc 17958 Hz Gain 0.9 dB Q 3.90
Filter 25: ON PK Fc 19056 Hz Gain -0.3 dB Q 2.26`

But doing the same with REW I got a different and I think a more exact result
Given this graph:
![REW EQ](https://user-images.githubusercontent.com/51036845/143625422-0073788a-a458-4bf4-b4a3-64a510cb8914.png)
and this PEQ:
`Preamp: -5.2 -> (added by me using EQApo)
Filter  1: ON  PK       Fc   188.0 Hz  Gain  -1.50 dB  Q  1.000
Filter  2: ON  PK       Fc    1082 Hz  Gain   2.40 dB  Q  1.003
Filter  3: ON  PK       Fc    2308 Hz  Gain  -3.00 dB  Q  2.307
Filter  4: ON  PK       Fc    2850 Hz  Gain -17.80 dB  Q  1.374
Filter  5: ON  PK       Fc    3618 Hz  Gain  18.00 dB  Q  1.001
Filter  6: ON  PK       Fc    5117 Hz  Gain -14.50 dB  Q  2.586
Filter  7: ON  PK       Fc    6031 Hz  Gain   3.40 dB  Q  3.914
Filter  8: ON  PK       Fc    6284 Hz  Gain   5.20 dB  Q  4.331
Filter  9: ON  PK       Fc    8575 Hz  Gain -21.00 dB  Q  3.554
Filter 10: ON  PK       Fc    8640 Hz  Gain  12.10 dB  Q  6.933
Filter 11: ON  PK       Fc   12814 Hz  Gain -10.70 dB  Q  3.641
Filter 12: ON  PK       Fc   14093 Hz  Gain -11.30 dB  Q  4.048
Filter 13: ON  PK       Fc   14160 Hz  Gain  18.00 dB  Q  1.000
Filter 14: ON  PK       Fc   15248 Hz  Gain -10.20 dB  Q  4.852
Filter 15: ON  PK       Fc   16096 Hz  Gain -13.70 dB  Q  5.000
Filter 16: ON  PK       Fc   16841 Hz  Gain -10.60 dB  Q  4.999
Filter 17: ON  PK       Fc   18696 Hz  Gain  -3.00 dB  Q  4.987`
What can I do to match the Target at the max?

**Comment by angelooo18** [comment] 2021-11-26 19:59
Thanks in advance

**Comment by jaakkopasanen** [comment] 2021-11-27 08:07
This is because AutoEq will limit the steepness of the equalizer frequency response slope to avoid eq filter ringing. There are some very steep ascends in your target (for example from 3 - 3.5 kHz) and AutoEq refuses to follow that steep slope. There is no parameter currently for managing the maximum steepness.

Closing the issue as AutoEq is working as intended.

**Closed by jaakkopasanen** 2021-11-27 08:07 UTC
