### ISSUE TITLE
Flat target? (for HRTF)

### ISSUE THREAD

**Issue by rpx91** [jaakkopasanen/AutoEq#64] opened 2019-07-12 10:17 UTC
(Not an issue, after guidance)

I read the documentation - I understand that there are target curves and their sources.

What I'd like to do is to use a flat target with oratory1990's as a source for the measurement. I understand how to target the already present curves with different measurement sources - but how do I say I want a flat target?

Use case - I want to try OOYH with a flat EQ rather than a Harmen target.

**Comment by jaakkopasanen** [comment] 2019-07-12 10:27
You can do this by setting compensation curve to zero: `--compensation=compensation/zero.csv`

**Comment by rpx91** [comment] 2019-07-13 07:11
Thanks for that - worked a charm. Now using flat in HeSuVi's Graphic EQ.

I'd also like to create a Fixed Band EQ for my Galaxy phone. It has a 9 band fixed band EQ. The default switch and precomputed results include 31hz which my s10 doesn't have. It has identical bands but htye start from 62.

I ran the following command

`python frequency_response.py --input_dir="flat-source" --output_dir="flat" --compensation="compensation\zero.csv" --equalize --parametric_eq --max_filters=5+5 --fixed_band_eq --fc 62,125,250,500,1000,2000,4000,8000,16000 --q 1.41
`
But I'm getting an error:

```
File "frequency_response.py", line 1827, in <module>
    FrequencyResponse.main(**FrequencyResponse.cli_args())
  File "frequency_response.py", line 1646, in main
    fs=fs
  File "frequency_response.py", line 1542, in process
    fbeq_filters, n_fbeq_filters, nfbeq_max_gains = self.optimize_fixed_band_eq(fc=fc, q=q, fs=fs)
  File "frequency_response.py", line 677, in optimize_fixed_band_eq
    fs=fs
  File "frequency_response.py", line 590, in optimize_biquad_filters
    _Q = _Q[sorted_inds]
IndexError: too many indices for array
```

I suspect user error rather than bug but I just couldn't get it working

**Comment by jaakkopasanen** [comment] 2019-07-14 10:17
I made some improvements and now what you were trying to do should work. The problem was caused because the same number of Q values were expected as there are Fc value, so 9 times 1.41 in this case. This has been a problem for some other users in the past so I changed it so that a single value is accepted and if only a single value is passed it will be used for all of the bands.

**Comment by rpx91** [comment] 2019-07-14 16:09
Thanks man! I did try inputting 1.41 9 times, but I got a different error.

It's pretty impressive - I can compute EQ's for the inbuilt DSP on the Astro A50 for example, or on the Sony XM3.

**Comment by jaakkopasanen** [comment] 2019-07-17 15:19
By the way I'm fairly sure equalizing an ear simulator measured frequency response flat is not the way to go for HRTF. Ear simulator measurements include the 3 kHz peak which is caused by ear canal resonance and should always be there.

Could you please close this issue if you feel like the problem doesn't exist anymore.

**Closed** 2019-07-17 16:19 UTC

**Comment by rpx91** [comment] 2019-07-17 16:48
Is there a target I can use? 

Idea is to use Impulcifer with IEMs. From using the flat EQ I've computed now it sounds much better than anything I've tried manually to compensate.
