### ISSUE TITLE
A way to increase equalization precision

### ISSUE THREAD

**Issue by lukaslt1993** [jaakkopasanen/AutoEq#430] opened 2022-03-14 08:53 UTC
Hey, I love how many results you could get and how it's nicely displayed in the graph. I have a feature request to introduce some kind of parameter to control the equalization precision.

Looks like the equalization now tries to get a good balance between execution time and precision but sometimes all I want is to have the equalized line as close to the target as possible no matter the execution time :)

It especially applies to spikes. For example, I'd like to give it more processing time so that 7.5k spike in this picture is close to the target when equalized. It's just to give an idea, some of my experiments have even more messy spikes :)
![image](https://user-images.githubusercontent.com/9968996/158135560-e849e9a9-c632-4f5a-8508-09058159b0f4.png)

**Comment by heavymetalmixer** [comment] 2022-03-14 13:36
I'd like to see more precision as well, and what are the cons if it's possible to go through that.

**Comment by Suznyan** [comment] 2022-03-31 05:53
Set --max_gain higher like `--max_gain=15` and change the frequency range of the smoothing `--treble_f_lower=11000 --treble_f_upper=20000`

**Comment by heavymetalmixer** [comment] 2022-04-01 14:14
> Set --max_gain higher like `--max_gain=15` and change the frequency range of the smoothing `--treble_f_lower=11000 --treble_f_upper=20000`

What do the last two do?

**Comment by jaakkopasanen** [comment] 2022-07-25 07:31
AutoEq has an algorithm for avoiding positive spikes in the equalizer frequency response because the narrow dips these would attempt to fix are not audible to humans and the sharp spikes in the equalizer can cause ringing. There is not way to get around this safe guard as it's basically never desired to do so (within the intended uses of this tool).

In other words: more precision wouldn't give you equalizer settings which make your headphones sound better.

I'll close the issue as AutoEq is working as designed.

**Closed by jaakkopasanen** 2022-07-25 07:31 UTC
