### ISSUE TITLE
KZ ZEX Pro request

### ISSUE THREAD

**Issue by harwey123** [jaakkopasanen/AutoEq#398] opened 2022-01-03 11:20 UTC
**Headphone requests**
Headphone requests are not welcome. If the headphones have not been measured by one of the supported sources, AutoEq cannot support it. If you happen to find a frequency response graph for the headphones, you can create eq settings yourself by following [this guide](https://medium.com/@jaakkopasanen/make-your-headphones-sound-supreme-1cbd567832a9). Open a headphone request issue only if the headphones have been measured by one of the supported sources but have not been added to AutoEq.

**Comment by AloeVera17** [comment] 2022-01-04 03:14
Here's a graph by [crinacle.com](https://crinacle.com/graphs/iems/kz-x-crinacle-crn-zex-pro/)

**Comment by jaakkopasanen** [comment] 2022-01-22 11:59
This is a duplicate of #392

**Closed by jaakkopasanen** 2022-01-22 11:59 UTC
