### ISSUE TITLE
Consider correcting phase as well as magnitude?

### ISSUE THREAD

**Issue by simontheflutist** [jaakkopasanen/AutoEq#58] opened 2019-06-15 23:42 UTC
This is a high-level feature request, and might be the first of its kind ever proposed. If we approximate headphones as having a transfer function, then we would say that at every frequency the headphone transfer function has both _magnitude_ and _phase_.

Much effort has been expended to correct for magnitude, but I am wondering if we can work towards creating convolution filters that correct phase distortion as well. Here is one way that might be possible.

1. Extract an impulse response for a particular set of headphones from InnerFidelity.
2. Take the Fourier transform of this impulse response, so we have a complex coefficient at every frequency.
3. Replace this Fourier transform with its inverse at every frequency.
4. Apply the inverse DFT to get a new time domain impulse response. This impulse response cancels out the impulse response that the headphones are effectively convolving _their_ input signal with.
5. Apply target response (e.g. Harman2017) to this impulse response.

**Comment by jaakkopasanen** [comment] 2019-06-17 17:25
I have thought about this but have never started to implement of even study the possible solutions.

Firstly almost no measurement database has phase data to begin with. Innerfidelity PDFs have phase graph and Crinacle has phase data for some IEMs. Nobody else have phase data because wast majority of headphones are minimum phase devices and therefore frequency magnitude response tells all there is to the frequency response of the headphone.

Secondly headphones being minimum phase devices I think that phase correction wouldn't actually provide any benefit. Room acoustics can benefit from phase correction because rooms are complex acoustical spaces and the dimensions are big enough to have significant impact on all frequencies. Correct me if I'm wrong.

Thirdly phase correction would only work with convolution impulse responses (FIR filters). Parametric eq (and fixed band eq) filters are minimum phase and cannot be anything else. I don't have numbers here but I suspect very few people are actually using the FIR filters perhaps because there aren't a lot of EQ softwares that support them. Phase corrections with FIR filters would also cause delays and pre-ringing and these two would probably outweigh the assumed benefits in most cases.

I might consider this if you have some evidence or sources indicating that phase correction for headphones would actually have a significant improvement for the perceived sound quality.

**Comment by simontheflutist** [comment] 2019-06-23 01:11
Thanks for the thoughtful response! I know how in theory it would be done, but after my first attempt I'm not sure it can work.

You're right that they don't show phase in the transfer function graph. But InnerFidelity shows impulse responses. If our headphones are approximated as LTI systems, they're fully characterized by their impulse responses. The DFT of the impulse response has frequency as well as phase data. Here's some pseudocode that demonstrates what I mean.
```python
# NumPy array of shape (N,) where N is the number of samples
headphone_impulse_response = load_headphone_impulse_response()
headphone_DFT = fft(headphone_impulse_response)
# ^ has the property that
#     convolve(foo, headphone_impulse_response)
#         = ifft(fft(foo) * fft(headphone_impulse_response))

# This could be other things as well. See below for more details.
target_impulse = [desired_strength, 0, 0, .... ]

# If headphone_impulse_response is relatively well-behaved then 
# most entries of its DFT are approximately 1+0j, and inverting it 
# element-wise should be fairly well-conditioned.
correction_DFT = 1 / headphone_DFT
correction_impulse_response = ifft(correction_DFT)
```
At this point `correction_impulse_response` has the property that if you convolve with it before or after convolving with `headphone_impulse_response`, you'll get back what you started with.
Of course this is full of problems.
   1. I digitized a phase plot from InnerFidelity and found that they are 1) noisy and 2) not robust against digitization error. I think we would have to ask IF for raw measurements, and I'm not sure if they're willing to help.
   2. This would work perfectly well if headphones were exactly minimum phase. But they're not. In my computations, I found that the impulse response I analyzed is not quite minimum phase. The inverse cannot be both causal and stable. I found that I could get a stable inverse impulse response if I relaxed the requirement that it be causal. I could not allow it to travel back in time, but I could allow it to output with some latency: `target impulse = [0] * num_wait_samples + [1, 0, 0, ....]`. (Note that if you had a desired composite transfer function, e.g. Harman 2017, you could apply EQ directly to `target_impulse`.)

I loaded my outputs into PulseEffects and it sounded really bad. But I don't want to give up yet, as I'm blaming the data.

About your third point: I am 100% convinced that phase matters, though I can't say how much yet. What I do know is that I can hear the difference between minimum and linear phase FIR filters generated by your script, and for some of my music I think the linear phase filter sounds better—pre-ringing is hardly noticeable. I suspect that many of the heuristic/fuzzy qualities of an audio system that audiophiles talk about boil down to phase characteristics. (Again we are thinking only linearly here)

**Comment by chjan** [comment] 2019-09-01 05:37
This is an interesting suggestion, perhaps not as a general feature, but for special cases. There is a never ending debate as to whether a minimum phase system (the normal case for headphones, and for speakers with this or that crossover filter), as compared to a linear phase (no phase shift) system, has any audible differences. 

If it is possible via convolution to correct phase for a number of well known headphones typically free of non-minimum artefacts, then the minimum phase vs linear phase versions could be directly compared through some AB testing. If setup on the web for people to evaluate, it could be the thread of the century. (I anticipate no audible differences, but that is my personal opinion). Such a test would educate the world in phase problematics. It could be done in coop with one of the main headphone sites. A very interesting idea!

**Comment by jaakkopasanen** [comment] 2019-09-05 09:17
I had a discussion with oratory1990 about this topic. I asked him if it would make sense to correct the phase and this was his response:
>Hi!
Excellent question - No, I don't think that would make sense, or rather, I DO, but it's already being adjusted when using minimum phase filters. keep in mind that every change in frequency response always goes hand in hand with a corresponding change in the phase response (as long as we're in the analog domain) meaning when we correct the frequency response, we automatically correct the phase response as well when using minimum phase filters. it's entirely possible to manipulate the phase response independently from the frequency response (and vice versa) using linear phase filters or allpass filters, but I don't see a meaningful application for headphones.

So minimum phase filters will correct the phase along with the magnitude response. He also confirmed that using minimum phase filters with EQ has the same effect as if the headphone designer tuned the headphone with mechanical and acoustical means.

Correcting phase problems of those few headphones that are not minimum phase devices is out of scope of this project. I might end up implementing the phase correction for room correction in [Impulcifer](https://github.com/jaakkopasanen/Impulcifer) but I don't know if the feature would find it's way into AutoEQ. Definitely this won't come part of the pre-computed results.

I'm closing the issue as the feature won't be implemented but feel free to continue discussion here. Closing the issue won't prevent adding new messages.

**Closed by jaakkopasanen** 2019-09-05 09:17 UTC

**Comment by chjan** [comment] 2019-09-05 09:52
So oratory1990 agrees with me, the audible effects are probably not present. Do you have an email to the right person on oratory1990, for further discussion? (Yes, I agree to your closing decision).

**Comment by jaakkopasanen** [comment] 2019-09-05 10:46
I don't have the guy's email address but he has a [reddit account](https://www.reddit.com/user/oratory1990) and a sub-reddit](https://www.reddit.com/r/oratory1990/).

**Comment by simontheflutist** [comment] 2019-09-05 18:30
> He also confirmed that using minimum phase filters with EQ has the same effect as if the headphone designer tuned the headphone with mechanical and acoustical means.

I now agree with closing this issue too. Although my rough computations suggested that headphones aren't _exactly_ minimum phase, the deviations are 1) likely imperceptible and 2) given our SNR, not correctable.
