### ISSUE TITLE
Drag and drop an audio file to the preview player

### ISSUE THREAD

**Issue by forestrf** [jaakkopasanen/AutoEq#764] opened 2024-01-26 23:43 UTC
**Is your feature request related to a problem? Please describe.**
The (part of the) song used does not showcase well the EQ in some cases (in my case with a pair of HD 599 it sounds mostly the same). When trying to find out if it's worth using an EQ before installing any, being able to preview the changes would help a lot.

**Describe the solution you'd like**
Being able to drag and drop a local audio file to the preview audio player.

**Describe alternatives you've considered**
Downloading the EQ and testing it locally, which requires more involvement.

**Additional context**
I was having problems with EasyEffects and Linux. I wanted to know if the problem was with the EQ file or the EasyEffects program. The problem was with the program, but it took me more effort to find out as the preview with EQ on autoeq.app sounded nearly the same. If I had the change to play one of the songs which I already know how they should sound, it would have helped.
I also want to convince a lazy friend to try using an EQ. Autoeq.app seems to be just one step away from offering the chance to find out if using an EQ is worth without needing to install any program and configure it, with the potential of not being worth it later and having to uninstall it. This would prevent wasting time to some while attract interest to others by quickly showing the difference an EQ makes,

**Comment by jaakkopasanen** [comment] 2024-02-10 10:30
Duplicate of #686

**Closed by jaakkopasanen** 2024-02-10 10:30 UTC
Labels: duplicate
