### ISSUE TITLE
Link to nowhere (404)

### ISSUE THREAD

**Issue by DrCWO** [jaakkopasanen/AutoEq#557] opened 2022-11-12 21:14 UTC
**Describe the bug**
On the restults page (https://github.com/jaakkopasanen/AutoEq/tree/master/results) the link: [AudioQuest NightHawk (Brainwavz HM5 hybrid earpads)](https://github.com/jaakkopasanen/AutoEq/blob/master/results/oratory1990/harman_over-ear_2018/AudioQuest%20NightHawk%20(Brainwavz%20HM5%20hybrid%20earpads)) goes to nowhere (404)

**To Reproduce**
Klick on "AudioQuest NightHawk (Brainwavz HM5 hybrid earpads"

**Expected behavior**
Page opens

**Files**

**System:**
 

**Additional context**

**Comment by jaakkopasanen** [comment] 2022-11-27 14:45
The issue is now fixed. I removed the result and added it back again. https://github.com/jaakkopasanen/AutoEq/tree/master/results/oratory1990/harman_over-ear_2018/AudioQuest%20NightHawk%20(Brainwavz%20HM5%20hybrid%20earpads)

**Closed by jaakkopasanen** 2022-11-27 14:45 UTC
Labels: hp request
