### ISSUE TITLE
Error with requirements tensorflow~=2.4.0 on Windows

### ISSUE THREAD

**Issue by JoaoCosta-EQ** [jaakkopasanen/AutoEq#367] opened 2021-11-10 02:27 UTC
**Describe the bug**
When I try to install the Auto EQ appears the following error:
ERROR: Could not find a version that satisfies the requirement tensorflow~=2.4.0 (from versions: none)
ERROR: No matching distribution found for tensorflow~=2.4.0 

**To Reproduce**
python -m pip install -U -r requirements.txt
On this part of the instalation it shows this error.

**Expected behavior**
I expect to finish installing the requirements without using the tensorflow as I did this process before and never neded.

**System:**
 - OS: [e.g. Windows 10]
 - Version latest one in CHANGELOG.md

**Additional context**
I tried installing in another PC that I have and it showed the same error.

**Comment by jaakkopasanen** [comment] 2021-11-21 07:06
This is duplicate of #358, #324 and #280.

Install Python 3.8.

**Closed by jaakkopasanen** 2021-11-21 07:06 UTC
