### ISSUE TITLE
Python script returns "Duplicate values found" where there are none

### ISSUE THREAD

**Issue by staticV3** [jaakkopasanen/AutoEq#529] opened 2022-09-23 22:37 UTC
**Describe the bug**
Python script returns "Duplicate values found" where there are none

**To Reproduce**
Put attached csv file into \AutoEQ\measurements\user
Run `python autoeq.py --input_dir="measurements/user" --output_dir="my_results/Truthear Zero" --compensation="compensation/harman_over-ear_2018.csv" --equalize --parametric_eq`

**Expected behavior**
I expect the python script to run

**Files**
[Crin Zero AVG Cal.csv](https://github.com/jaakkopasanen/AutoEq/files/9637356/Crin.Zero.AVG.Cal.csv)

**System:**
 - OS: Windows 10
 - Version: can't find which AutoEQ versions. Last git pull: 24.09.2022

**Additional context**
worked fine before the big update to the EQ optimizer

**Comment by jaakkopasanen** [comment] 2022-09-24 10:22
Thanks for reporting this bug! I found the culprit and it should be fixed now. Please confirm and close the ticket if the issue is solved for you.

**Closed** 2022-10-26 22:05 UTC
