### ISSUE TITLE
QCY T17

### ISSUE THREAD

**Issue by SoxxZ** [jaakkopasanen/AutoEq#674] opened 2023-06-20 14:12 UTC
Got the frequency response from here: https://www.head-fi.org/showcase/qcy-t17-bluetooth-5-1-youth-bud-tws.25539/reviews#review-27217

![QCY_Comparison](https://github.com/jaakkopasanen/AutoEq/assets/14855972/8a1ed238-be0e-4ed2-8b4b-86085aad620a)

Used the Web Plot Digitizer, and got this data: 
[qcyt17.csv](https://github.com/jaakkopasanen/AutoEq/files/11801324/qcyt17.csv)

It worked with Wavelet, but for some reason Pulse-effects can't load the generated impulse file, so i am opening the issue because i don't know how to fix it, and also to add the buds to the list.

**Comment by jaakkopasanen** [comment] 2023-08-09 07:57
This seems duplicate of #685 

Please follow that issue. I'll close this one.

**Closed by jaakkopasanen** 2023-08-09 07:57 UTC
